using UnityEngine;

// Handles all of the player ship's movement: sliding left/right and up/down
// inside a boxed play area, auto-scrolling forward, and a bit of cosmetic
// banking/pitching so it looks like a ship reacting to input instead of a
// box sliding around on rails.
//
// IMPORTANT ARCHITECTURE NOTE (read this if you're wondering why input
// reading and physics are split across two different methods below):
// this used to do everything - reading input AND applying Rigidbody
// forces - inside Update(). That's a real bug, not just a style choice.
// Unity's physics engine steps on its own fixed timestep via FixedUpdate,
// completely decoupled from however fast your monitor happens to be
// rendering frames. Calling rb.AddForce / setting rb.velocity from Update()
// means the number of force impulses applied per second scales with your
// framerate instead of the physics engine's actual step rate - at 200fps
// you're firing way more impulses per second than at 60fps, and neither
// lines up cleanly with what the physics solver expects. The visible
// result is tiny, inconsistent jitter in the Rigidbody's motion - easy to
// miss on the ship itself, but a following camera sits right on top of it
// and turns that jitter into visible shake (this is exactly what we were
// chasing while setting up Cinemachine - lower camera damping was
// "revealing" the jitter instead of smoothing over it).
//
// The fix: read input every rendered frame in Update() (so controls still
// feel responsive), but only touch the Rigidbody inside FixedUpdate() (so
// physics stays consistent regardless of framerate). This is the standard
// pattern anytime a script both reads input and drives a Rigidbody.
[RequireComponent(typeof(Rigidbody))]
public class PlayerMovement : MonoBehaviour
{
    [Header("Movement Speeds")]
    [Tooltip("How fast the ship slides left/right in response to input.")]
    public float sidewaysSpeed = 6f;

    [Tooltip("How fast the ship slides up/down in response to input.")]
    public float verticalSpeed = 6f;

    [Tooltip("Constant forward speed - this is what makes the ship feel like it's always advancing, regardless of left/right/up/down input.")]
    public float forwardSpeed = 8f;

    [Header("Play Area Bounds")]
    [Tooltip("The ship is clamped inside this box on the X/Y plane so it can't fly off past the edges of the playfield. min must be less than max on both axes - see OnValidate below.")]
    public float minMovementX = -10f;
    public float maxMovementX = 10f;
    public float minMovementY = -10f;
    public float maxMovementY = 10f;

    [Header("Physics Feel")]
    [Tooltip("How quickly leftover sideways/vertical velocity bleeds off once you let go of input. NOTE: setting this to exactly 0 doesn't mean 'no damping applied gently' - it means damping is completely disabled, since Lerp with a time of 0 just returns the starting value unchanged. Keep this above 0.")]
    public float forceDecay = 0.5f;

    [Tooltip("Hard cap on forward velocity, so accumulated forward force doesn't build up indefinitely.")]
    public float maxZVelocity = 10f;

    [Header("Banking / Tilt (cosmetic only - doesn't affect actual movement)")]
    [Tooltip("How quickly the ship rotates into its target tilt angle. Higher = snappier, lower = floatier.")]
    public float rotationSpeed = 10f;

    [Tooltip("Max bank angle applied when moving left/right. (Yes, the name says X but it's driven by horizontal input - that naming carried over from the original script and isn't worth breaking serialized Inspector values to fix.)")]
    public float maxRotationAngleX = 45f;

    [Tooltip("Max pitch angle applied when moving up/down. (Same naming quirk as above, just for the vertical axis.)")]
    public float maxRotationAngleY = 10f;

    // Cached input values, read fresh every rendered frame in Update() and
    // then consumed by FixedUpdate() whenever the physics engine actually
    // steps - possibly multiple times per rendered frame, or less than
    // once per frame, depending on framerate vs physics timestep. Either
    // way, FixedUpdate always works off the most recent input we've seen.
    private float xInput;
    private float yInput;
    private Rigidbody rb;
    private Vector3 movement;

    // Generated wrapper class from PlayerControls.inputactions. Don't
    // hand-edit this class directly anywhere - it's regenerated by Unity
    // whenever the .inputactions asset changes, so any manual edits to the
    // generated file would just get silently overwritten.
    private PlayerControls controls;

    private void Awake()
    {
        controls = new PlayerControls();
        rb = GetComponent<Rigidbody>();

        // This is a zero-gravity space game with no ground to land on, so
        // gravity should never be acting on the ship - forcing it off here
        // in code means it's simply never a variable again, regardless of
        // what's checked in the Inspector on any given prefab or scene.
        rb.useGravity = false;

        // Interpolation smooths the ship's *rendered* position between
        // physics steps, rather than only updating what you see exactly
        // when FixedUpdate happens to run. Between this and moving our
        // physics code into FixedUpdate above, this should meaningfully
        // reduce the jitter a following camera was picking up on. "Interpolate"
        // is the right choice here (as opposed to "Extrapolate", which
        // guesses ahead and can overshoot on sudden direction changes).
        rb.interpolation = RigidbodyInterpolation.Interpolate;
    }

    private void OnEnable()
    {
        // The new Input System requires explicitly enabling an action map
        // before it'll respond to anything - unlike the old Input.GetAxis,
        // which just always worked whether you wanted it to or not. Doing
        // this in OnEnable (and disabling in OnDisable below) means input
        // automatically stops being read the moment this GameObject gets
        // deactivated - e.g. when the game-over screen takes over.
        controls.Gameplay.Enable();
    }

    private void OnDisable()
    {
        controls.Gameplay.Disable();
    }

    private void Start()
    {
        Cursor.visible = false; // fullscreen space game, we don't want a mouse cursor floating around
    }

    private void Update()
    {
        // Only reading input here - nothing that touches the Rigidbody.
        // This runs every rendered frame so controls feel immediately
        // responsive, but the values just sit cached until FixedUpdate
        // actually consumes them below.
        Vector2 moveInput = controls.Gameplay.Move.ReadValue<Vector2>();
        xInput = moveInput.x;
        yInput = moveInput.y;
    }

    private void FixedUpdate()
    {
        // Everything that touches the Rigidbody lives here instead, so it
        // runs in lockstep with the physics engine's own timestep rather
        // than at whatever rate the screen happens to be rendering.
        Move();
    }

    private void Move()
    {
        // Figure out where we'd end up if we moved this step, then clamp
        // that target position to the play area bounds. We clamp the
        // target position rather than the final movement vector so the
        // ship firmly stops at the wall instead of jittering against it.
        //
        // Note we're using Time.fixedDeltaTime here now instead of
        // Time.deltaTime - inside FixedUpdate, Unity actually sets
        // Time.deltaTime to the same value anyway, but fixedDeltaTime
        // states our intent explicitly rather than relying on that quirk.
        float dt = Time.fixedDeltaTime;

        float clampedX = Mathf.Clamp(transform.position.x + (xInput * sidewaysSpeed * dt), minMovementX, maxMovementX);
        float clampedY = Mathf.Clamp(transform.position.y + (yInput * verticalSpeed * dt), minMovementY, maxMovementY);

        // The actual force we apply is "how far we need to move to get from
        // where we are to that clamped target" on X/Y, plus a constant
        // forward push on Z so the ship is always advancing.
        movement = new Vector3(clampedX - transform.position.x, clampedY - transform.position.y, forwardSpeed * dt);
        rb.AddForce(movement, ForceMode.Impulse);

        // Purely cosmetic tilt - doesn't affect where the ship actually
        // goes, just makes it look like it's banking into turns instead of
        // sliding around like a hovering brick.
        float rotationAngleX = 0f;
        float rotationAngleY = 0f;

        if (yInput < 0f)
        {
            rotationAngleX = Mathf.Lerp(0f, maxRotationAngleY, -yInput);
        }
        else if (yInput > 0f)
        {
            rotationAngleX = Mathf.Lerp(0f, -maxRotationAngleY, yInput);
        }

        if (xInput < 0f)
        {
            rotationAngleY = Mathf.Lerp(0f, -maxRotationAngleX, -xInput);
        }
        else if (xInput > 0f)
        {
            rotationAngleY = Mathf.Lerp(0f, maxRotationAngleX, xInput);
        }

        // Using rb.MoveRotation instead of setting transform.rotation
        // directly - for a non-kinematic Rigidbody being driven by physics,
        // MoveRotation lets the physics engine account for the rotation
        // change correctly (and plays nicely with Interpolate above),
        // rather than yanking the transform around outside of physics'
        // awareness.
        Quaternion targetRotation = Quaternion.Slerp(transform.rotation, Quaternion.Euler(rotationAngleX, 0f, rotationAngleY), rotationSpeed * dt);
        rb.MoveRotation(targetRotation);

        // Finally, damp out any sideways/vertical velocity that's built up
        // (so the ship doesn't keep drifting once you release input), while
        // still letting forward (Z) velocity ride, capped at a max.
        rb.velocity = new Vector3(
            Mathf.Lerp(rb.velocity.x, 0f, forceDecay * dt),
            Mathf.Lerp(rb.velocity.y, 0f, forceDecay * dt),
            Mathf.Clamp(rb.velocity.z, -maxZVelocity, maxZVelocity)
        );
    }

    // Runs automatically in the Editor whenever a field on this script is
    // changed in the Inspector (and once when the object loads). This is
    // the safety net for the bounds bug we chased earlier in this project:
    // min/max values that are equal or swapped, which silently pull the
    // ship toward a single fixed point instead of throwing an obvious
    // error. Now it gets caught and reported the moment it happens.
    private void OnValidate()
    {
        if (minMovementX >= maxMovementX)
        {
            Debug.LogWarning($"[PlayerMovement] minMovementX ({minMovementX}) should be less than maxMovementX ({maxMovementX}) on '{name}' - the ship will get constantly pulled toward a single X position instead of being able to move freely. Auto-correcting to a safe default range.", this);
            minMovementX = -10f;
            maxMovementX = 10f;
        }

        if (minMovementY >= maxMovementY)
        {
            Debug.LogWarning($"[PlayerMovement] minMovementY ({minMovementY}) should be less than maxMovementY ({maxMovementY}) on '{name}' - the ship will get constantly pulled toward a single Y position instead of being able to move freely. Auto-correcting to a safe default range.", this);
            minMovementY = -10f;
            maxMovementY = 10f;
        }

        if (forceDecay <= 0f)
        {
            Debug.LogWarning($"[PlayerMovement] forceDecay is {forceDecay} on '{name}' - a value of 0 or less disables velocity damping entirely (Lerp with a time of 0 does nothing), which can let leftover velocity from collisions or other scripts persist indefinitely. Consider a small positive value like 0.5 instead.", this);
        }
    }
}